CC := g++
CFLAGS := -Wall
TARGET := hw4_2
v := 1

all: $(TARGET)

$(TARGET):C44111227_hw4_2.cpp
	$(CC) -o $@ $^ -lpthread

judge: all
	@judge -v ${v} || printf "or \`make judge v=1\`"

clean:
	rm -f $(TARGET)
